### ISSUE TITLE
Volume mounts are read only 

### ISSUE THREAD

**Issue by jjnavsofs0** [OT-CONTAINER-KIT/mongodb-operator#50]
I created a cluster using this operator in EKS and for persistent storage used ebs csi drivers. The cluster creation failed as the /data/db folder was read only and lockfile couldn't be generated.

**Comment by iamabhishek-dubey** [comment]
Please try adding securityContext

https://github.com/OT-CONTAINER-KIT/mongodb-operator/blob/9862fc23979212c018d76120ca5ac44705b417c0/examples/security-context/clusterd.yaml#L11
